INSERT IGNORE INTO country (name) VALUES
('Afghanistan'), ('Albania'), ('Algeria'), ('American Samoa'), ('Andorra'),
('Angola'), ('Argentina'), ('Armenia'), ('Australia'), ('Austria'),
('Azerbaijan'), ('Bahamas'), ('Bahrain'), ('Bangladesh'), ('Belarus'),
('Belgium'), ('Belize'), ('Bolivia'), ('Bosnia and Herzegovina'), ('Botswana'),
('Brazil'), ('Bulgaria'), ('Cambodia'), ('Cameroon'), ('Canada'),
('Chile'), ('China'), ('Colombia'), ('Croatia'), ('Cuba'),
('Czech Republic'), ('Denmark'), ('Ecuador'), ('Egypt'), ('El Salvador'),
('Estonia'), ('Ethiopia'), ('Finland'), ('France'), ('Georgia'),
('Germany'), ('Ghana'), ('Greece'), ('Guatemala'), ('Honduras'),
('Hungary'), ('Iceland'), ('India'), ('Indonesia'), ('Iran'),
('Iraq'), ('Ireland'), ('Israel'), ('Italy'), ('Jamaica'),
('Japan'), ('Jordan'), ('Kazakhstan'), ('Kenya'), ('Kuwait'),
('Latvia'), ('Lebanon'), ('Libya'), ('Lithuania'), ('Luxembourg'),
('Malaysia'), ('Mali'), ('Malta'), ('Mexico'), ('Moldova'),
('Monaco'), ('Mongolia'), ('Montenegro'), ('Morocco'), ('Netherlands'),
('New Zealand'), ('Nicaragua'), ('Nigeria'), ('Norway'), ('Pakistan'),
('Panama'), ('Paraguay'), ('Peru'), ('Philippines'), ('Poland'),
('Portugal'), ('Qatar'), ('Romania'), ('Russia'), ('Saudi Arabia'),
('Senegal'), ('Serbia'), ('Singapore'), ('Slovakia'), ('Slovenia'),
('Somalia'), ('South Africa'), ('South Korea'), ('Spain'), ('Sri Lanka'),
('Sudan'), ('Sweden'), ('Switzerland'), ('Syria'), ('Taiwan'),
('Thailand'), ('Tunisia'), ('Turkey'), ('Ukraine'), ('United Arab Emirates'),
('United Kingdom'), ('United States'), ('Uruguay'), ('Venezuela'),
('Vietnam'), ('Yemen'), ('Zimbabwe');